import { RedirectToSignIn, SignedIn, SignedOut } from "@clerk/nextjs";
import { ArrowLeftIcon, ArrowRightIcon } from "lucide-react";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import React from "react";
import HeadEditor from "~/components/HeadEditor";

export default function EditId() {
  const router = useRouter()
  const dbId = parseInt(router.query.id as string)

  return (
    <>
      <Head>
        <title>- Deco -</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SignedOut>
        <RedirectToSignIn />
      </SignedOut>
      <SignedIn>
        <main className="flex min-h-screen flex-col items-center bg-gradient-to-b bg-stone-950 text-white p-4">
          <h1 className="text-4xl font-bold p-2">
            Deco - Heads
          </h1>
          <div className="flex gap-10 justify-center items-start">
            <Link href={"/edit/" + (dbId - 1)} className="bg-stone-900 p-2 rounded-md">
              <ArrowLeftIcon className="w-8 h-8" />
            </Link>
            <div className="container bg-stone-900 flex p-2 rounded-md">
              <HeadEditor dbId={dbId} actionType="UPDATE" />
            </div>
            <Link href={"/edit/" + (dbId + 1)} className="bg-stone-900 p-2 rounded-md">
              <ArrowRightIcon className="w-8 h-8" />
            </Link>
          </div>
        </main>
      </SignedIn>
    </>
  );
}