import { RedirectToSignIn, SignedIn, SignedOut } from "@clerk/nextjs";
import { ArrowLeftIcon, ArrowRightIcon } from "lucide-react";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import React from "react";
import HeadEditor from "~/components/HeadEditor";
import Header from "~/components/header";
import { Button } from "~/components/ui/button";
import { H1 } from "~/components/ui/typography";

export default function EditId() {
  const router = useRouter()
  const dbId = parseInt(router.query.id as string)

  return (
    <>
      <Head>
        <title>- Deco -</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SignedOut>
        <RedirectToSignIn />
      </SignedOut>
      <SignedIn>
        <Header />
        <main className="flex min-h-screen flex-col items-center bg-background text-foreground">
          <Link href="/" className="pb-4"><H1>Head editor</H1></Link>
          <div className="flex gap-10 justify-center items-start">
            <Link href={"/edit/" + (dbId - 1)} className="p-2 rounded-md">
              <Button variant="outline" className="w-10 h-10 p-0"><ArrowLeftIcon /></Button>
            </Link>
            <div className="container flex p-2 rounded-md">
              <HeadEditor dbId={dbId} actionType="UPDATE" />
            </div>
            <Link href={"/edit/" + (dbId + 1)} className="p-2 rounded-md">
              <Button variant="outline" className="w-10 h-10 p-0"><ArrowRightIcon /></Button>
            </Link>
          </div>
        </main>
      </SignedIn>
    </>
  );
}