import { RedirectToSignIn, SignedIn, SignedOut } from "@clerk/nextjs";
import { Button, Link, TextField } from "@mui/material";
import Head from "next/head";
import * as React from "react";
import { useEffect } from "react";
import { api } from "~/utils/api";

export default function Import() {
  const [field, setField] = React.useState("")
  const [buttonStatus, setButtonStatus] = React.useState("IDLE")
  const { mutate, isSuccess } = api.db.update.useMutation()

  useEffect(() => {
    if (isSuccess) {
      setField("")
      setButtonStatus("SUCCESS")
      // wait 1 second
      setTimeout(() => {
        setButtonStatus("IDLE")
      }, 1000)
    }
  }, [isSuccess])

  function handleValidate() {
    const keys = field.split("\n")

    for (const key of keys) {
      mutate({ name: "UNKNOWN", tags: [], key, actionType: "INSERT" })
    }

    return true
  }

  return (
    <>
      <Head>
        <title>- Deco -</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SignedOut>
        <RedirectToSignIn />
      </SignedOut>
      <SignedIn>
        <main className="flex min-h-screen flex-col items-center bg-gradient-to-b bg-stone-950 text-white p-4">
          <Link href="/" className="text-4xl font-bold pb-4">
            Deco - Heads
          </Link>
          <div className="container bg-stone-900 m-1 flex flex-col p-2 rounded-md">
            <TextField
              id="outlined-multiline-static"
              label="Keys"
              multiline
              rows={4}
              placeholder="74d028cd9236b2fb49ef4c104184bc2bd1ab8a89ec2596fe6c3724d24f569445"
              className="w-full"
              value={field}
              onChange={(e) => setField(e.target.value)}
            />
            <div className="grow flex flex-col-reverse">
              <Button
                variant="contained"
                onClick={() => handleValidate()}
                color={buttonStatus === "SUCCESS" ? "success" : buttonStatus === "FAIL" ? "error" : "primary"}
                className="w-fit"
              >
                {buttonStatus === "SUCCESS" ? "OK!" : buttonStatus === "FAIL" ? "ERROR!" : "Validate"}
              </Button>
            </div>
          </div>
        </main>
      </SignedIn>
    </>
  )
}