import { RedirectToSignIn, SignedIn, SignedOut } from "@clerk/nextjs";
import Head from "next/head";
import React from "react";
import HeadEditor from "~/components/HeadEditor";

export default function EditNew() {
  const dbId = Math.floor(Math.random() * 100000)

  return (
    <>
      <Head>
        <title>- Deco -</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SignedOut>
        <RedirectToSignIn />
      </SignedOut>
      <SignedIn>
        <main className="flex min-h-screen flex-col items-center bg-gradient-to-b bg-stone-950 text-white p-4">
          <h1 className="text-4xl font-bold p-2">
            Deco - Heads
          </h1>
          <div className="container bg-stone-900 m-1 flex p-2 rounded-md">
            <HeadEditor dbId={dbId} actionType="INSERT" />
          </div>
        </main>
      </SignedIn>
    </>
  );
}