import { Button } from "@mui/material";
import Head from "next/head";
import { MinecraftHeadViewer } from "~/HeadViewer";
import { api } from "~/utils/api";
import React from "react";
import { ZodHeadsRowObject } from "~/zod";
import Link from "next/link";

export default function Home() {
  const { data: dbData } = api.db.getAll.useQuery();
  const [detailsOpened, setDetailsOpened] = React.useState(false);

  return (
    <>
      <Head>
        <title>- Deco -</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center bg-gradient-to-b bg-stone-950 text-white p-4">
        <h1 className="text-4xl font-bold p-2">
          Deco - Heads
        </h1>
        <div className="container bg-stone-900 m-1 grid grid-cols-10 p-2 rounded-md">
          {dbData?.results.rows.map((item) => {
            try {
              const obj = ZodHeadsRowObject.parse(item);

              return <div key={obj.heads_id} className={"flex flex-col items-center justify-start"}>
                <MinecraftHeadViewer
                  skin={"http://textures.minecraft.net/texture/" + obj.heads_key}
                  width={100}
                  height={100}
                />
                <Link href={`/edit/${obj.heads_id}`} className="text-stone-300 underline text-center">
                  {obj.heads_name}
                </Link>
              </div>
            } catch (err) {
              console.error(err);
              return "Shit happened"
            }
          })}
        </div>
        <div className="container bg-stone-900 m-1 p-2 rounded-md flex flex-col">
          <Button onClick={() => setDetailsOpened(!detailsOpened)} className="w-fit">
            {detailsOpened ? "Hide" : "Show"} JSON
          </Button>
          {detailsOpened && (
            <p className="container bg-stone-950 p-2 rounded-md">
              {JSON.stringify(dbData?.results.rows)}
            </p>
          )}
        </div>
      </main>
    </>
  );
}
